"""posts_comments_테이블_생성

Revision ID: 50577aec0522
Revises: (없음 - 첫 번째 마이그레이션)
Create Date: 2026-03-10 20:58:16.352039

[Flyway 비교]
Flyway:  V1__create_posts_comments.sql 파일에 SQL을 직접 작성
Alembic: autogenerate 로 SQLAlchemy 모델을 분석하여 이 파일을 자동 생성

[주요 개념]
- revision: 이 마이그레이션의 고유 ID (Git 커밋 해시처럼 고유합니다)
- down_revision: 이전 마이그레이션 ID (None = 최초 마이그레이션)
- upgrade(): 앞으로 적용 (alembic upgrade head)    → Flyway migrate
- downgrade(): 이전으로 되돌리기 (alembic downgrade -1) → Flyway undo (유료)
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50577aec0522'
down_revision: Union[str, Sequence[str], None] = None  # 이전 버전 없음 (최초)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    마이그레이션 적용 (DB 스키마를 최신 상태로 업그레이드)

    alembic upgrade head 명령 실행 시 호출됩니다.
    Flyway의 V1__*.sql 파일의 내용과 동일한 역할입니다.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # posts 테이블 생성
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='게시글 제목'),
    sa.Column('content', sa.Text(), nullable=False, comment='게시글 내용'),
    sa.Column('author', sa.String(length=50), nullable=False, comment='작성자'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='작성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='댓글 내용'),
    sa.Column('author', sa.String(length=50), nullable=False, comment='작성자'),
    sa.Column('post_id', sa.Integer(), nullable=False, comment='게시글 ID (외래 키)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='작성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    마이그레이션 롤백 (이전 상태로 되돌리기)

    alembic downgrade -1 명령 실행 시 호출됩니다.
    Flyway 무료 버전에는 없는 기능으로, Alembic의 강점 중 하나입니다.
    테이블 삭제 순서: comments(외래 키 보유) → posts(참조 대상) 순서로 삭제해야 합니다.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')  # 외래 키가 있는 테이블 먼저 삭제
    op.drop_table('posts')
    # ### end Alembic commands ###
