"""posts_조회수_컬럼_추가

Revision ID: fab35d9a67d1
Revises: 50577aec0522
Create Date: 2026-03-10 20:59:40.288585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab35d9a67d1'
down_revision: Union[str, Sequence[str], None] = '50577aec0522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', sa.Integer(), server_default='0', nullable=False, comment='조회수'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('view_count')

    # ### end Alembic commands ###
